# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_lzCompress <- function(object, level) {
    .Call(`_genser_do_lzCompress`, object, level)
}

do_lzUncompress <- function(raw) {
    .Call(`_genser_do_lzUncompress`, raw)
}

do_zstdCompress <- function(object, level) {
    .Call(`_genser_do_zstdCompress`, object, level)
}

do_zstdUncompress <- function(raw) {
    .Call(`_genser_do_zstdUncompress`, raw)
}

do_snappyCompress <- function(object, level) {
    .Call(`_genser_do_snappyCompress`, object, level)
}

do_snappyUncompress <- function(raw) {
    .Call(`_genser_do_snappyUncompress`, raw)
}

